version: '3.8'

services:
  frontend:
    build: ./front-ababa-movie
    ports:
      - '5173:5173'
    container_name: ababa_frontend
    depends_on:
      - backend

  backend:
    build: ./back-ababa-movie
    ports:
      - '5000:5000'
    container_name: ababa_backend
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: breakme
      POSTGRES_PASSWORD: gimmeajob
      POSTGRES_DB: ababamovies
    ports:
      - '5432:5432'
    container_name: ababa_postgres

volumes:
  pgdata: